run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  govet:
    enable-all: false
    enable:
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
        - staticcheck
    - path: internal/layers/apisecurity/jwt\.go
      linters:
        - staticcheck
      text: "elliptic.Unmarshal has been deprecated"
    - path: internal/acme/client\.go
      linters:
        - unparam
      text: "result 1 .error. is always nil"
  max-issues-per-linter: 50
  max-same-issues: 5
