package virtualpatch

import (
	"regexp"
	"strings"
	"time"
)

// Generator generates virtual patches from CVE data.
type Generator struct {
	// Pattern templates for different attack types
	templates map[string]AttackPattern
}

// AttackPattern defines patterns for an attack type.
type AttackPattern struct {
	Name        string
	Description string
	Patterns    []PatchPattern
	Indicators  []string // Keywords that trigger this pattern
}

// NewGenerator creates a new patch generator.
func NewGenerator() *Generator {
	return &Generator{
		templates: defaultTemplates(),
	}
}

// Generate creates a virtual patch from a CVE entry.
func (g *Generator) Generate(cve *CVEEntry) *VirtualPatch {
	if !g.shouldGenerate(cve) {
		return nil
	}

	// Determine attack type from CVE description
	attackType := g.detectAttackType(cve)

	// Generate patterns based on attack type
	patterns := g.generatePatterns(cve, attackType)

	if len(patterns) == 0 {
		return nil
	}

	// Determine severity
	severity := g.determineSeverity(cve)

	// Create patch
	patch := &VirtualPatch{
		ID:          generatePatchID(cve.CVEID),
		CVEID:       cve.CVEID,
		Name:        generatePatchName(cve),
		Description: cve.Description,
		GeneratedAt: time.Now(),
		Patterns:    patterns,
		Action:      g.determineAction(severity),
		Score:       g.calculateScore(cve),
		Severity:    severity,
		MatchLogic:  "or",
		Enabled:     true,
		AutoGenerated: true,
	}

	return patch
}

// shouldGenerate determines if a patch should be generated for this CVE.
func (g *Generator) shouldGenerate(cve *CVEEntry) bool {
	// Must be network/web attack
	if !g.isWebAttack(cve) {
		return false
	}

	// Must have sufficient severity
	if cve.CVSSScore < 5.0 && cve.Severity != "HIGH" && cve.Severity != "CRITICAL" {
		return false
	}

	return true
}

// isWebAttack checks if CVE is a web/network attack.
func (g *Generator) isWebAttack(cve *CVEEntry) bool {
	webKeywords := []string{
		"http", "web", "injection", "xss", "sqli", "rce", "lfi", "rfi",
		"traversal", "upload", "request", "header", "cookie", "parameter",
		"jndi", "deserialization", "ssrf", "csrf", "command", "shell",
	}

	desc := strings.ToLower(cve.Description)
	for _, kw := range webKeywords {
		if strings.Contains(desc, kw) {
			return true
		}
	}

	// Check CWEs
	webCWEs := []string{"CWE-79", "CWE-89", "CWE-94", "CWE-22", "CWE-502", "CWE-918"}
	for _, cwe := range cve.CWEs {
		for _, webCWE := range webCWEs {
			if cwe == webCWE {
				return true
			}
		}
	}

	return false
}

// detectAttackType determines the attack type from CVE.
func (g *Generator) detectAttackType(cve *CVEEntry) string {
	desc := strings.ToLower(cve.Description)

	// Check for specific attack types
	attackTypes := map[string][]string{
		"jndi":           {"jndi", "log4j", "log4shell"},
		"deserialization": {"deserialization", "unserialize", "object injection"},
		"sqli":           {"sql injection", "sqli", "blind sql"},
		"xss":            {"cross-site scripting", "xss", "script injection"},
		"rce":            {"remote code execution", "rce", "command execution", "shell"},
		"lfi":            {"local file inclusion", "lfi", "path traversal", "../"},
		"ssrf":           {"server-side request forgery", "ssrf"},
		"upload":         {"file upload", "unrestricted upload", "arbitrary file"},
		"header":         {"header injection", "http header", "host header"},
		"xxe":            {"xml external entity", "xxe"},
	}

	for attackType, keywords := range attackTypes {
		for _, kw := range keywords {
			if strings.Contains(desc, kw) {
				return attackType
			}
		}
	}

	return "generic"
}

// generatePatterns creates detection patterns for the attack.
func (g *Generator) generatePatterns(cve *CVEEntry, attackType string) []PatchPattern {
	patterns := []PatchPattern{}

	desc := strings.ToLower(cve.Description)

	switch attackType {
	case "jndi":
		patterns = append(patterns,
			PatchPattern{Type: "body", Pattern: "${jndi:", MatchType: "contains"},
			PatchPattern{Type: "query", Pattern: "${jndi:", MatchType: "contains"},
			PatchPattern{Type: "header", Key: "User-Agent", Pattern: "${jndi:", MatchType: "contains"},
		)

	case "deserialization":
		patterns = append(patterns,
			PatchPattern{Type: "body", Pattern: "rO0", MatchType: "contains"}, // Java serialized
			PatchPattern{Type: "body", Pattern: `Yml0\+`, MatchType: "contains"}, // PHP
			PatchPattern{Type: "content_type", Pattern: "application/x-java-serialized-object", MatchType: "contains"},
		)

	case "sqli":
		// Extract table/column mentions from description
		patterns = append(patterns,
			PatchPattern{Type: "query", Pattern: "(union|select|insert|update|delete|drop|create|alter|exec|execute)", MatchType: "regex"},
			PatchPattern{Type: "body", Pattern: "(union|select|insert|update|delete|drop|create|alter|exec|execute)", MatchType: "regex"},
		)

	case "xss":
		patterns = append(patterns,
			PatchPattern{Type: "query", Pattern: "<script", MatchType: "contains"},
			PatchPattern{Type: "body", Pattern: `(?i)(<script|javascript:|onerror=|onload=|eval\()`, MatchType: "regex"},
		)

	case "rce":
		patterns = append(patterns,
			PatchPattern{Type: "query", Pattern: `([;|\x60]|\$\(|\$\{)`, MatchType: "regex"},
			PatchPattern{Type: "body", Pattern: `([;|\x60]|\$\(|\$\{)`, MatchType: "regex"},
		)

	case "lfi":
		patterns = append(patterns,
			PatchPattern{Type: "query", Pattern: `(\.\./|\.\.\\|%2e%2e%2f|%2e%2e/)`, MatchType: "regex"},
			PatchPattern{Type: "path", Pattern: `(\.\./|\.\.\\)`, MatchType: "regex"},
		)

	case "ssrf":
		patterns = append(patterns,
			PatchPattern{Type: "query", Pattern: "(http://|https://|file://|dict://|gopher://)", MatchType: "regex"},
			PatchPattern{Type: "body", Pattern: "(http://|https://|file://|dict://|gopher://)", MatchType: "regex"},
		)

	case "upload":
		patterns = append(patterns,
			PatchPattern{Type: "path", Pattern: `(\.(php|jsp|asp|aspx|exe|sh|bat))$`, MatchType: "regex"},
			PatchPattern{Type: "content_type", Pattern: "application/x-php|application/x-httpd-php", MatchType: "regex"},
		)

	case "header":
		patterns = append(patterns,
			PatchPattern{Type: "header", Key: "Host", Pattern: "[\r\n]", MatchType: "regex"},
			PatchPattern{Type: "header", Key: "Content-Type", Pattern: "[\r\n]", MatchType: "regex"},
		)

	case "xxe":
		patterns = append(patterns,
			PatchPattern{Type: "body", Pattern: "<!ENTITY.*SYSTEM", MatchType: "regex"},
			PatchPattern{Type: "body", Pattern: "<!DOCTYPE.*<!ENTITY", MatchType: "regex"},
		)

	default:
		// Generic patterns based on description keywords
		keywords := g.extractKeywords(desc)
		for _, kw := range keywords {
			patterns = append(patterns,
				PatchPattern{Type: "query", Pattern: kw, MatchType: "contains"},
				PatchPattern{Type: "body", Pattern: kw, MatchType: "contains"},
			)
		}
	}

	return patterns
}

// determineSeverity determines patch severity from CVE.
func (g *Generator) determineSeverity(cve *CVEEntry) string {
	if cve.Severity != "" {
		return cve.Severity
	}

	// Based on CVSS score
	if cve.CVSSScore >= 9.0 {
		return "CRITICAL"
	}
	if cve.CVSSScore >= 7.0 {
		return "HIGH"
	}
	if cve.CVSSScore >= 4.0 {
		return "MEDIUM"
	}
	return "LOW"
}

// determineAction determines the action based on severity.
func (g *Generator) determineAction(severity string) string {
	switch severity {
	case "CRITICAL":
		return "block"
	case "HIGH":
		return "block"
	case "MEDIUM":
		return "log"
	default:
		return "log"
	}
}

// calculateScore calculates the WAF score.
func (g *Generator) calculateScore(cve *CVEEntry) int {
	// Base score on CVSS
	score := int(cve.CVSSScore * 5) // Scale to 0-50

	// Adjust based on severity
	switch cve.Severity {
	case "CRITICAL":
		score = 50
	case "HIGH":
		if score < 40 {
			score = 40
		}
	case "MEDIUM":
		if score < 25 {
			score = 25
		}
	}

	// Cap at 50
	if score > 50 {
		score = 50
	}

	return score
}

// extractKeywords extracts attack keywords from description.
var (
	reKeywords = regexp.MustCompile(`["'](\w+)["']|(\w+)\(|param\w+|\b(union|select|insert|update|delete|drop|create|exec|eval)\b`)
	reProduct  = regexp.MustCompile(`(?i)(apache|nginx|wordpress|drupal|joomla|laravel|spring|struts)[\s\w]*`)
)

func (g *Generator) extractKeywords(desc string) []string {
	// Simple keyword extraction
	keywords := []string{}

	// Look for quoted strings, function names, parameter names
	matches := reKeywords.FindAllStringSubmatch(desc, -1)

	for _, match := range matches {
		for _, m := range match {
			if m != "" && len(m) > 2 {
				keywords = append(keywords, m)
			}
		}
	}

	// Deduplicate
	seen := make(map[string]bool)
	unique := []string{}
	for _, kw := range keywords {
		if !seen[kw] {
			seen[kw] = true
			unique = append(unique, kw)
		}
	}

	return unique
}

// generatePatchID generates a patch ID from CVE ID.
func generatePatchID(cveID string) string {
	return "VP-" + strings.ReplaceAll(cveID, "-", "")
}

// generatePatchName generates a patch name.
func generatePatchName(cve *CVEEntry) string {
	// Extract product from description
	name := "Virtual Patch for " + cve.CVEID

	// Try to extract product name
	matches := reProduct.FindString(cve.Description)
	if matches != "" {
		name = "VP " + matches + " " + cve.CVEID
	}

	return name
}

// defaultTemplates returns default attack pattern templates.
func defaultTemplates() map[string]AttackPattern {
	return map[string]AttackPattern{
		"log4shell": {
			Name:        "Log4Shell",
			Description: "Log4j JNDI injection",
			Indicators:  []string{"jndi", "log4j", "ldap", "rmi", "dns"},
			Patterns: []PatchPattern{
				{Type: "body", Pattern: "${jndi:", MatchType: "contains"},
				{Type: "header", Key: "User-Agent", Pattern: "${jndi:", MatchType: "contains"},
			},
		},
		"spring4shell": {
			Name:        "Spring4Shell",
			Description: "Spring Data Binding RCE",
			Indicators:  []string{"spring", "class.module", "classLoader"},
			Patterns: []PatchPattern{
				{Type: "query", Pattern: "class.module", MatchType: "contains"},
				{Type: "body", Pattern: "class.module", MatchType: "contains"},
			},
		},
		"shellshock": {
			Name:        "Shellshock",
			Description: "Bash environment variable RCE",
			Indicators:  []string{"bash", "shellshock", "() { :; }"},
			Patterns: []PatchPattern{
				{Type: "header", Key: "User-Agent", Pattern: "() { :; }", MatchType: "contains"},
			},
		},
	}
}
