package virtualpatch

import (
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/guardianwaf/guardianwaf/internal/engine"
)

// Layer implements virtual patching for known CVEs.
type Layer struct {
	config    *Config
	database  *Database

	// Compiled patterns for performance
	compiledPatterns map[string]*regexp.Regexp

	// Last update time
	lastUpdate time.Time

	// Auto-update
	nvdClient   *NVDClient
	stopUpdate  chan struct{}
	updateWg    sync.WaitGroup

	// Statistics
	updateCount atomic.Int64
	lastError   atomic.Value

	mu sync.RWMutex
}

// NewLayer creates a new virtual patching layer.
func NewLayer(config *Config) *Layer {
	if config == nil {
		config = DefaultConfig()
	}

	layer := &Layer{
		config:           config,
		database:         NewDatabase(),
		compiledPatterns: make(map[string]*regexp.Regexp),
		lastUpdate:       time.Time{},
	}

	// Load default patches
	layer.loadDefaultPatches()

	// Initialize NVD client if auto-update enabled
	if config.AutoUpdate {
		layer.nvdClient = NewNVDClient("")
		if config.NVDFeedURL != "" {
			layer.nvdClient.SetBaseURL(config.NVDFeedURL)
		}
		layer.stopUpdate = make(chan struct{})
		layer.startAutoUpdate()
	}

	return layer
}

// startAutoUpdate starts the background auto-update goroutine.
func (l *Layer) startAutoUpdate() {
	l.updateWg.Add(1)
	go func() {
		defer l.updateWg.Done()

		ticker := time.NewTicker(l.config.UpdateInterval)
		defer ticker.Stop()

		// Run initial update
		l.runUpdate()

		for {
			select {
			case <-ticker.C:
				l.runUpdate()
			case <-l.stopUpdate:
				return
			}
		}
	}()
}

// runUpdate fetches latest CVEs from NVD.
func (l *Layer) runUpdate() {
	if l.nvdClient == nil {
		return
	}

	// Search for recent high/critical CVEs
	opts := SearchOptions{
		ResultsPerPage: 20,
		PubStartDate:   time.Now().AddDate(0, 0, -7), // Last 7 days
		Severity:       "HIGH",
	}

	resp, err := l.nvdClient.Search(opts)
	if err != nil {
		l.lastError.Store(err)
		return
	}

	for _, item := range resp.Vulnerabilities {
		entry := convertToCVEEntry(item.CVE)
		if entry != nil {
			// Auto-generate patches if enabled
			if l.config.AutoGenerateRules {
				patches := l.generatePatchesFromCVE(entry)
				entry.Patches = append(entry.Patches, patches...)
			}
			l.database.AddCVE(entry)
		}
	}

	l.updateCount.Add(1)
	l.mu.Lock()
	l.lastUpdate = time.Now()
	l.mu.Unlock()
}

// generatePatchesFromCVE generates virtual patches from CVE data.
func (l *Layer) generatePatchesFromCVE(entry *CVEEntry) []VirtualPatch {
	var patches []VirtualPatch

	// Generate pattern based on CVE description
	patterns := extractPatternsFromDescription(entry.Description)

	if len(patterns) > 0 {
		patch := VirtualPatch{
			ID:            fmt.Sprintf("VP-%s", entry.CVEID),
			CVEID:         entry.CVEID,
			Name:          fmt.Sprintf("Auto-generated patch for %s", entry.CVEID),
			Description:   entry.Description,
			GeneratedAt:   time.Now(),
			Patterns:      patterns,
			Action:        "block",
			Score:         int(entry.CVSSScore * 5), // Scale to 0-50
			Severity:      entry.Severity,
			MatchLogic:    "or",
			Enabled:       true,
			AutoGenerated: true,
		}
		patches = append(patches, patch)
	}

	return patches
}

// extractPatternsFromDescription extracts detection patterns from CVE description.
func extractPatternsFromDescription(desc string) []PatchPattern {
	var patterns []PatchPattern
	descLower := strings.ToLower(desc)

	// Common attack patterns
	attackPatterns := map[string][]string{
		"sql injection":    {"sql", "injection", "sqli"},
		"xss":              {"xss", "cross-site scripting", "cross site scripting"},
		"rce":              {"rce", "remote code execution", "command execution"},
		"path traversal":   {"path traversal", "directory traversal", "../"},
		"lfi":              {"lfi", "local file inclusion", "file inclusion"},
		"rfi":              {"rfi", "remote file inclusion"},
		"xxe":              {"xxe", "xml external entity"},
		"ssrf":             {"ssrf", "server-side request forgery"},
	}

	for attackType, keywords := range attackPatterns {
		for _, keyword := range keywords {
			if strings.Contains(descLower, keyword) {
				// Add pattern based on attack type
				switch attackType {
				case "sql injection":
					patterns = append(patterns, PatchPattern{
						Type:      "body",
						Pattern:   "(?i)(union|select|insert|update|delete|drop|';|\";|--|#)",
						MatchType: "regex",
					})
				case "xss":
					patterns = append(patterns, PatchPattern{
						Type:      "body",
						Pattern:   "(?i)(<script|javascript:|onerror=|onload=|alert\\()",
						MatchType: "regex",
					})
				case "path traversal":
					patterns = append(patterns, PatchPattern{
						Type:      "path",
						Pattern:   "(\\.\\./|\\.\\.\\\\|%2e%2e%2f)",
						MatchType: "regex",
					})
				case "rce":
					patterns = append(patterns, PatchPattern{
						Type:      "body",
						Pattern:   "(;|\\\\||`|\\$\\(|\\$\\{)",
						MatchType: "regex",
					})
				}
				break
			}
		}
	}

	return patterns
}

// Stop stops the auto-update goroutine.
func (l *Layer) Stop() {
	if l.stopUpdate != nil {
		close(l.stopUpdate)
		l.updateWg.Wait()
	}
}

// GetUpdateStats returns auto-update statistics.
func (l *Layer) GetUpdateStats() UpdateStats {
	l.mu.RLock()
	lastUpdate := l.lastUpdate
	l.mu.RUnlock()

	lastErr, _ := l.lastError.Load().(error)
	var lastErrorStr string
	if lastErr != nil {
		lastErrorStr = lastErr.Error()
	}

	return UpdateStats{
		UpdateCount: l.updateCount.Load(),
		LastUpdate:  lastUpdate,
		LastError:   lastErrorStr,
	}
}

// UpdateStats represents auto-update statistics.
type UpdateStats struct {
	UpdateCount int64     `json:"update_count"`
	LastUpdate  time.Time `json:"last_update"`
	LastError   string    `json:"last_error,omitempty"`
}

// Name returns the layer name.
func (l *Layer) Name() string {
	return "virtualpatch"
}

// Process implements the engine.Layer interface.
func (l *Layer) Process(ctx *engine.RequestContext) engine.LayerResult {
	if !l.config.Enabled {
		return engine.LayerResult{Action: engine.ActionPass}
	}
	if ctx.TenantWAFConfig != nil && !ctx.TenantWAFConfig.VirtualPatch.Enabled {
		return engine.LayerResult{Action: engine.ActionPass}
	}

	// Get all active patches
	patches := l.database.GetActivePatches()

	findings := []engine.Finding{}
	totalScore := 0

	for _, patch := range patches {
		if !patch.Enabled {
			continue
		}

		// Check if severity is in block list
		if !l.shouldBlock(patch.Severity) {
			continue
		}

		// Match patch patterns
		matched, details := l.matchPatch(ctx, patch)
		if matched {
			// Create finding
			finding := engine.Finding{
				DetectorName: l.Name(),
				Category:     patch.CVEID,
				Description:  fmt.Sprintf("Virtual Patch: %s - %s", patch.Name, patch.Description),
				MatchedValue: details,
				Location:     "virtualpatch",
			}
			findings = append(findings, finding)
			totalScore += patch.Score

			// Update hit stats
			l.recordHit(patch.ID)

			// If action is block, return immediately
			if patch.Action == "block" {
				return engine.LayerResult{
					Action:   engine.ActionBlock,
					Findings: findings,
					Score:    totalScore,
				}
			}
		}
	}

	// Check if we should block based on total score
	if totalScore >= 50 {
		return engine.LayerResult{
			Action:   engine.ActionBlock,
			Findings: findings,
			Score:    totalScore,
		}
	}

	// Log findings but pass
	if len(findings) > 0 {
		return engine.LayerResult{
			Action:   engine.ActionLog,
			Findings: findings,
			Score:    totalScore,
		}
	}

	return engine.LayerResult{
		Action: engine.ActionPass,
	}
}

// matchPatch checks if a request matches a virtual patch.
func (l *Layer) matchPatch(ctx *engine.RequestContext, patch *VirtualPatch) (bool, string) {
	if len(patch.Patterns) == 0 {
		return false, ""
	}

	// Evaluate all patterns based on logic
	andLogic := patch.MatchLogic == "and" || patch.MatchLogic == ""

	matchedCount := 0
	details := []string{}

	for _, pattern := range patch.Patterns {
		matched := l.matchPattern(ctx, pattern)

		if matched {
			matchedCount++
			details = append(details, fmt.Sprintf("%s:%s matched", pattern.Type, pattern.Key))

			// OR logic: first match is enough
			if !andLogic {
				return true, strings.Join(details, ", ")
			}
		}
	}

	// AND logic: all patterns must match
	if andLogic && matchedCount == len(patch.Patterns) {
		return true, strings.Join(details, ", ")
	}

	return false, ""
}

// matchPattern checks a single pattern.
func (l *Layer) matchPattern(ctx *engine.RequestContext, pattern PatchPattern) bool {
	value := l.getValueByType(ctx, pattern.Type, pattern.Key)

	if value == "" {
		return false
	}

	switch pattern.MatchType {
	case "exact":
		return value == pattern.Pattern
	case "contains":
		return strings.Contains(value, pattern.Pattern)
	case "starts_with":
		return strings.HasPrefix(value, pattern.Pattern)
	case "ends_with":
		return strings.HasSuffix(value, pattern.Pattern)
	case "regex":
		return l.matchRegex(value, pattern.Pattern)
	default:
		// Default to contains
		return strings.Contains(value, pattern.Pattern)
	}
}

// getValueByType extracts value from request based on type.
func (l *Layer) getValueByType(ctx *engine.RequestContext, typ, key string) string {
	switch typ {
	case "path":
		return ctx.Path
	case "query":
		if ctx.Request != nil && ctx.Request.URL != nil {
			return ctx.Request.URL.RawQuery
		}
		return ""
	case "header":
		if ctx.Headers != nil {
			if vals, ok := ctx.Headers[http.CanonicalHeaderKey(key)]; ok && len(vals) > 0 {
				return vals[0]
			}
		}
		return ""
	case "body":
		if ctx.BodyString != "" {
			return ctx.BodyString
		}
		if ctx.Body != nil {
			return string(ctx.Body)
		}
		return ""
	case "method":
		return ctx.Method
	case "user_agent":
		if ctx.Headers != nil {
			if vals, ok := ctx.Headers["User-Agent"]; ok && len(vals) > 0 {
				return vals[0]
			}
		}
		return ""
	case "content_type":
		if ctx.Headers != nil {
			if vals, ok := ctx.Headers["Content-Type"]; ok && len(vals) > 0 {
				return vals[0]
			}
		}
		return ""
	case "uri":
		if ctx.Request != nil && ctx.Request.URL != nil {
			return ctx.Request.URL.RequestURI()
		}
		return ctx.Path
	case "client_ip":
		if ctx.ClientIP != nil {
			return ctx.ClientIP.String()
		}
		return ""
	default:
		return ""
	}
}

// matchRegex matches value against regex pattern.
func (l *Layer) matchRegex(value, pattern string) bool {
	l.mu.RLock()
	re, ok := l.compiledPatterns[pattern]
	l.mu.RUnlock()

	if !ok {
		// Compile and cache
		compiled, err := regexp.Compile(pattern)
		if err != nil {
			return false
		}

		l.mu.Lock()
		l.compiledPatterns[pattern] = compiled
		l.mu.Unlock()
		re = compiled
	}

	return re.MatchString(value)
}

// shouldBlock checks if a severity level should be blocked.
func (l *Layer) shouldBlock(severity string) bool {
	severity = strings.ToUpper(severity)
	for _, s := range l.config.BlockSeverity {
		if strings.ToUpper(s) == severity {
			return true
		}
	}
	return false
}

// recordHit records a patch hit.
func (l *Layer) recordHit(patchID string) {
	l.mu.Lock()
	defer l.mu.Unlock()

	patch := l.database.GetPatch(patchID)
	if patch != nil {
		patch.Hits++
		patch.LastHit = &time.Time{}
		*patch.LastHit = time.Now()
	}
}

// AddPatch adds a custom patch.
func (l *Layer) AddPatch(patch *VirtualPatch) {
	l.mu.Lock()
	defer l.mu.Unlock()

	l.database.patches[patch.ID] = patch
}

// DisablePatch disables a patch.
func (l *Layer) DisablePatch(patchID string) bool {
	l.mu.Lock()
	defer l.mu.Unlock()

	patch := l.database.GetPatch(patchID)
	if patch != nil {
		patch.Enabled = false
		return true
	}
	return false
}

// EnablePatch enables a patch.
func (l *Layer) EnablePatch(patchID string) bool {
	l.mu.Lock()
	defer l.mu.Unlock()

	patch := l.database.GetPatch(patchID)
	if patch != nil {
		patch.Enabled = true
		return true
	}
	return false
}

// GetPatch returns a patch by ID.
func (l *Layer) GetPatch(patchID string) *VirtualPatch {
	return l.database.GetPatch(patchID)
}

// GetActivePatches returns all active patches.
func (l *Layer) GetActivePatches() []*VirtualPatch {
	return l.database.GetActivePatches()
}

// GetStats returns statistics.
func (l *Layer) GetStats() DatabaseStats {
	return l.database.Stats()
}

// loadDefaultPatches loads built-in patches for common vulnerabilities.
func (l *Layer) loadDefaultPatches() {
	// Log4Shell (CVE-2021-44228)
	l.database.AddCVE(&CVEEntry{
		CVEID:       "CVE-2021-44228",
		Description: "Apache Log4j2 JNDI Injection",
		CVSSScore:   10.0,
		Severity:    "CRITICAL",
		Source:      "nvd",
		Active:      true,
		Patches: []VirtualPatch{
			{
				ID:          "VP-LOG4SHELL-001",
				CVEID:       "CVE-2021-44228",
				Name:        "Log4Shell JNDI Injection",
				Description: "Block Log4j JNDI lookup patterns",
				GeneratedAt: time.Now(),
				Patterns: []PatchPattern{
					{Type: "body", Pattern: "${jndi:", MatchType: "contains"},
					{Type: "query", Pattern: "${jndi:", MatchType: "contains"},
					{Type: "header", Key: "User-Agent", Pattern: "${jndi:", MatchType: "contains"},
					{Type: "header", Key: "X-Forwarded-For", Pattern: "${jndi:", MatchType: "contains"},
				},
				Action:     "block",
				Score:      50,
				Severity:   "CRITICAL",
				MatchLogic: "or",
				Enabled:    true,
			},
		},
	})

	// Spring4Shell (CVE-2022-22965)
	l.database.AddCVE(&CVEEntry{
		CVEID:       "CVE-2022-22965",
		Description: "Spring Framework RCE via Data Binding",
		CVSSScore:   9.8,
		Severity:    "CRITICAL",
		Source:      "nvd",
		Active:      true,
		Patches: []VirtualPatch{
			{
				ID:          "VP-SPRING4SHELL-001",
				CVEID:       "CVE-2022-22965",
				Name:        "Spring4Shell RCE",
				Description: "Block Spring Data Binding attack patterns",
				GeneratedAt: time.Now(),
				Patterns: []PatchPattern{
					{Type: "query", Pattern: "class.module", MatchType: "contains"},
					{Type: "body", Pattern: "class.module", MatchType: "contains"},
				},
				Action:     "block",
				Score:      50,
				Severity:   "CRITICAL",
				MatchLogic: "or",
				Enabled:    true,
			},
		},
	})

	// Shellshock (CVE-2014-6271)
	l.database.AddCVE(&CVEEntry{
		CVEID:       "CVE-2014-6271",
		Description: "GNU Bash RCE via environment variables",
		CVSSScore:   10.0,
		Severity:    "CRITICAL",
		Source:      "nvd",
		Active:      true,
		Patches: []VirtualPatch{
			{
				ID:          "VP-SHELLSHOCK-001",
				CVEID:       "CVE-2014-6271",
				Name:        "Shellshock Bash RCE",
				Description: "Block Shellshock attack vectors",
				GeneratedAt: time.Now(),
				Patterns: []PatchPattern{
					{Type: "header", Key: "User-Agent", Pattern: "() { :; }", MatchType: "contains"},
					{Type: "header", Key: "Cookie", Pattern: "() { :; }", MatchType: "contains"},
					{Type: "header", Key: "Referer", Pattern: "() { :; }", MatchType: "contains"},
				},
				Action:     "block",
				Score:      50,
				Severity:   "CRITICAL",
				MatchLogic: "or",
				Enabled:    true,
			},
		},
	})

	// WordPress REST API Vulnerability
	l.database.AddCVE(&CVEEntry{
		CVEID:       "CVE-2017-1001000",
		Description: "WordPress REST API privilege escalation",
		CVSSScore:   7.5,
		Severity:    "HIGH",
		Source:      "custom",
		Active:      true,
		Patches: []VirtualPatch{
			{
				ID:          "VP-WP-REST-001",
				CVEID:       "CVE-2017-1001000",
				Name:        "WordPress REST API Exploit",
				Description: "Block unauthorized REST API access",
				GeneratedAt: time.Now(),
				Patterns: []PatchPattern{
					{Type: "path", Pattern: "^/wp-json/wp/v[0-9]+/users", MatchType: "regex"},
				},
				Action:     "log",
				Score:      30,
				Severity:   "HIGH",
				MatchLogic: "and",
				Enabled:    true,
			},
		},
	})
}
