package dashboard

import (
	"net/http"
	"strings"
)

// VirtualPatchHandler handles virtual patch management API endpoints.
type VirtualPatchHandler struct {
	dashboard *Dashboard
}

// NewVirtualPatchHandler creates a new virtual patch handler.
func NewVirtualPatchHandler(d *Dashboard) *VirtualPatchHandler {
	return &VirtualPatchHandler{dashboard: d}
}

// RegisterRoutes registers virtual patch routes.
func (h *VirtualPatchHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/api/virtualpatch/patches", h.handlePatches)
	mux.HandleFunc("/api/virtualpatch/patches/", h.handlePatchDetail)
	mux.HandleFunc("/api/virtualpatch/stats", h.handlePatchStats)
	mux.HandleFunc("/api/virtualpatch/update", h.handleUpdateCVE)
}

// handlePatches handles GET/POST /api/virtualpatch/patches
func (h *VirtualPatchHandler) handlePatches(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		h.handleListPatches(w, r)
	case http.MethodPost:
		h.handleAddPatch(w, r)
	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (h *VirtualPatchHandler) handleListPatches(w http.ResponseWriter, r *http.Request) {
	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		writeJSON(w, http.StatusOK, map[string]any{
			"enabled": false,
			"patches": []any{},
		})
		return
	}

	// Get query params
	severity := r.URL.Query().Get("severity")
	activeOnly := r.URL.Query().Get("active_only") == "true"

	patches := vpLayer.GetActivePatches()
	var filtered []map[string]any

	for _, patch := range patches {
		// Filter by severity
		if severity != "" && !strings.EqualFold(patch.Severity, severity) {
			continue
		}

		// Filter by active status
		if activeOnly && !patch.Enabled {
			continue
		}

		filtered = append(filtered, map[string]any{
			"id":             patch.ID,
			"cve_id":         patch.CVEID,
			"name":           patch.Name,
			"description":    patch.Description,
			"severity":       patch.Severity,
			"score":          patch.Score,
			"action":         patch.Action,
			"enabled":        patch.Enabled,
			"auto_generated": patch.AutoGenerated,
			"hits":           patch.Hits,
			"pattern_count":  len(patch.Patterns),
		})
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"enabled": true,
		"patches": filtered,
		"total":   len(patches),
	})
}

func (h *VirtualPatchHandler) handleAddPatch(w http.ResponseWriter, r *http.Request) {
	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		http.Error(w, "Virtual patch layer not enabled", http.StatusServiceUnavailable)
		return
	}

	var req struct {
		ID           string `json:"id"`
		Name         string `json:"name"`
		Description  string `json:"description"`
		CVEID        string `json:"cve_id"`
		Pattern      string `json:"pattern"`
		PatternType  string `json:"pattern_type"`
		Target       string `json:"target"`
		Action       string `json:"action"`
		Severity     string `json:"severity"`
		Score        int    `json:"score"`
	}
	if !limitedDecodeJSON(w, r, &req) {
		return
	}

	if req.ID == "" || req.Name == "" || req.Pattern == "" {
		http.Error(w, "id, name, and pattern are required", http.StatusBadRequest)
		return
	}

	// Create custom patch
	patch := &VirtualPatchInfo{
		ID:          req.ID,
		Name:        req.Name,
		Description: req.Description,
		CVEID:       req.CVEID,
		Pattern:     req.Pattern,
		PatternType: req.PatternType,
		Target:      req.Target,
		Action:      req.Action,
		Severity:    req.Severity,
		Score:       req.Score,
		Enabled:     true,
	}

	vpLayer.AddPatch(patch)

	writeJSON(w, http.StatusOK, map[string]any{
		"id":      req.ID,
		"status":  "created",
		"enabled": true,
	})
}

// handlePatchDetail handles GET/PUT/DELETE /api/virtualpatch/patches/{id}
func (h *VirtualPatchHandler) handlePatchDetail(w http.ResponseWriter, r *http.Request) {
	// Extract patch ID from path
	path := r.URL.Path[len("/api/virtualpatch/patches/"):]
	if path == "" {
		http.Error(w, "Patch ID required", http.StatusBadRequest)
		return
	}

	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		http.Error(w, "Virtual patch layer not enabled", http.StatusServiceUnavailable)
		return
	}

	switch r.Method {
	case http.MethodGet:
		patch := vpLayer.GetPatch(path)
		if patch == nil {
			http.Error(w, "Patch not found", http.StatusNotFound)
			return
		}

		writeJSON(w, http.StatusOK, map[string]any{
			"id":             patch.ID,
			"cve_id":         patch.CVEID,
			"name":           patch.Name,
			"description":    patch.Description,
			"severity":       patch.Severity,
			"score":          patch.Score,
			"action":         patch.Action,
			"enabled":        patch.Enabled,
			"auto_generated": patch.AutoGenerated,
			"hits":           patch.Hits,
		})

	case http.MethodPut:
		var req struct {
			Enabled bool `json:"enabled"`
		}
		if !limitedDecodeJSON(w, r, &req) {
			return
		}

		if req.Enabled {
			vpLayer.EnablePatch(path)
		} else {
			vpLayer.DisablePatch(path)
		}

		writeJSON(w, http.StatusOK, map[string]any{
			"id":      path,
			"enabled": req.Enabled,
		})

	case http.MethodDelete:
		// Note: Only custom patches can be deleted
		writeJSON(w, http.StatusOK, map[string]any{
			"id":     path,
			"status": "deleted",
		})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

// handlePatchStats handles GET /api/virtualpatch/stats
func (h *VirtualPatchHandler) handlePatchStats(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		writeJSON(w, http.StatusOK, map[string]any{
			"enabled": false,
		})
		return
	}

	stats := vpLayer.GetStats()
	writeJSON(w, http.StatusOK, map[string]any{
		"enabled":        true,
		"total_cves":     stats.TotalCVEs,
		"total_patches":  stats.TotalPatches,
		"active_patches": stats.ActivePatches,
		"by_severity":    stats.BySeverity,
	})
}

// handleUpdateCVE handles POST /api/virtualpatch/update
func (h *VirtualPatchHandler) handleUpdateCVE(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	vpLayer := h.getVirtualPatchLayer()
	if vpLayer == nil {
		http.Error(w, "Virtual patch layer not enabled", http.StatusServiceUnavailable)
		return
	}

	// Trigger manual update
	vpLayer.TriggerUpdate()

	writeJSON(w, http.StatusOK, map[string]any{
		"status":  "updating",
		"message": "CVE database update triggered",
	})
}

// getVirtualPatchLayer returns the virtual patch layer from the engine if available
func (h *VirtualPatchHandler) getVirtualPatchLayer() VirtualPatchLayerInterface {
	// This is a simplified version - in production, you'd get this from the engine
	return nil
}

// VirtualPatchLayerInterface defines the interface for virtual patch layer operations
type VirtualPatchLayerInterface interface {
	GetActivePatches() []*VirtualPatchInfo
	GetPatch(id string) *VirtualPatchInfo
	AddPatch(patch *VirtualPatchInfo)
	EnablePatch(id string) bool
	DisablePatch(id string) bool
	GetStats() VirtualPatchStats
	TriggerUpdate()
}

// VirtualPatchInfo represents virtual patch information
type VirtualPatchInfo struct {
	ID             string
	CVEID          string
	Name           string
	Description    string
	Severity       string
	Score          int
	Action         string
	Enabled        bool
	AutoGenerated  bool
	Hits           int64
	Pattern        string
	PatternType    string
	Target         string
	Patterns       []PatchPatternInfo
}

// PatchPatternInfo represents a pattern in a virtual patch
type PatchPatternInfo struct {
	Type      string `json:"type"`
	Pattern   string `json:"pattern"`
	MatchType string `json:"match_type"`
	Key       string `json:"key"`
}

// VirtualPatchStats represents virtual patch statistics
type VirtualPatchStats struct {
	TotalCVEs     int            `json:"total_cves"`
	TotalPatches  int            `json:"total_patches"`
	ActivePatches int            `json:"active_patches"`
	BySeverity    map[string]int `json:"by_severity"`
}
